services:
  dockge:
    image: louislam/dockge:1
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PATH_TO_DATA}:/app/data
      - ${PATH_TO_STACK}:${PATH_TO_STACK}
    environment:
      - DOCKGE_STACKS_DIR=${PATH_TO_STACK}
    restart: unless-stopped
